import { SearchFilterFormValue } from '../interfaces/search-filter-form-value.interface';

export const SearchFilterFormFields: { [key in keyof SearchFilterFormValue]: string } = {
  query: 'query',
  country: 'country',
  city: 'city',
  category: 'category',
  subcategory: 'subcategory',
  tags: 'tags',
  isOnlineBooking: 'isOnlineBooking',
  isInstantBooking: 'isInstantBooking',
  dateFrom: 'dateFrom',
  dateTo: 'dateTo',
  timeFrom: 'timeFrom',
  timeTo: 'timeTo',
  isOnlineService: 'isOnlineService',
  isAtMasterLocationService: 'isAtMasterLocationService',
  isAtClientLocationService: 'isAtClientLocationService',
  priceCurrency: 'priceCurrency',
  priceStart: 'priceStart',
  priceEnd: 'priceEnd',
  rating: 'rating',
  professionalLevel: 'professionalLevel',
  paymentMethods: 'paymentMethods',
  onlyWithReviews: 'onlyWithReviews',
  onlyWithPhotos: 'onlyWithPhotos',
  onlyWithFixedPrice: 'onlyWithFixedPrice',
  onlyWithCertificates: 'onlyWithCertificates',
  nationalities: 'nationalities',
  languages: 'languages',
  experience: 'experience',
  startAge: 'startAge',
  endAge: 'endAge',
};
